OLD_NORSE_CORPUS_FILES = "data/"
VECTOR_SPACE = 300
CONTEXT_LENGTH = 6
NON_INFLECTING = ["xAP", "xCC", "xCS", "xIT", "xIM", "xRP", "xUA", "xCU"]
MIN_WORD_COUNT = 1
MENOTA_PICKLE = "cache/menodata.p"
STOPWORDS = "á,af,annathvárt,at,ateins,eins,eða,ef,eftir,ei,eigi,en,engi,enn,fyrir,fyrr,fyrri,heldr,hjá,hvaðan,hvárr,hvat,hvatvetna,hvergi,í,ífrá,jafnan,með,mót,né,nema,nú,nøkkurr,oft,ok,ór,sem,svá,þar,þaðan,þegar,þó,þóat,um,undan,undir,upp,vel,yfir,ǽ,til"
LEMMA_W2V_MODEL = "models/lemmatized_vectors.w2v"
NORMALIZED_W2V_MODEL = "models/normalized_vectors.w2v"
LEMMATIZER_MODEL = "models/lemmatizer.model"
AMIBGUOUS_DICT_PICKLE = "cache/ambiguous_forms.p"
UNIQUE_DICT_PICKLE = "cache/unique_forms.p"
WORD_INDEX_PICKLE = "cache/word_index.p"